In [1]:
import pandas as pd 
import numpy as np 
df = pd.read_csv(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Kaggle\Date and Time.csv")
df.head(4)

         date  product_id  city_id  orders
0  10/12/2019        5628       25       3
1  15/08/2018        3646       14     157
2  23/10/2018        1859       25       1
3  17/08/2019        7292       25       1

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

## Converting First Strring into Date

In [5]:
df["date"] = pd.to_datetime(df["date"] , dayfirst = True)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

In [11]:
df[df["date"] > "2019-12-6"]

          date  product_id  city_id  orders
0   2019-12-10        5628       25       3
48  2019-12-11        2860       28      41
90  2019-12-16        7491       13       1
127 2019-12-16        3828       11       1
146 2019-12-13        6828       13       1
147 2019-12-09        5290        3     139
148 2019-12-10         561       13       1
158 2019-12-16        2148       28      51
203 2019-12-16        4033        4       1
216 2019-12-13        3493       26       9
220 2019-12-14        4482       28       2
237 2019-12-09        5489       13      23
246 2019-12-10        2253       13      46
259 2019-12-10        7246       13       1
266 2019-12-11         972       13       1
411 2019-12-11        3179       22      16
453 2019-12-13        3860       22       1
505 2019-12-12        2585       25       1
512 2019-12-12        4968       28       2
539 2019-12-08        2831       16       4
554 2019-12-11         873       25      26
626 2019-12-07        6668       28       1
651 2019-12-12         763       26      25
815 2019-12-08        3659       20       4
867 2019-12-16         335       13       3
892 2019-12-07        1564       13      96
929 2019-12-07        6801        3       7

In [24]:
df["Date_Year"] = df["date"].dt.year
df["Date_Month"] = df["date"].dt.month
df["Day"] = df["date"].dt.day_name()
df["Is Weekend"] = np.where(df["Day"].isin(["Saturday" , "Sunday"]), 1,0)

In [27]:
df.head(8)

,date,product_id,city_id,orders,Date_Year,Date_Month,Day,Is Weekend
0,2019-12-10,5628,25,3,2019,12,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,Saturday,1
4,2019-01-06,4344,25,3,2019,1,Sunday,1
5,2018-08-23,1811,25,4,2018,8,Thursday,0
6,2018-11-21,1282,26,1,2018,11,Wednesday,0
7,2019-03-27,5022,2,41,2019,3,Wednesday,0

In [34]:
df["Quarter"] = df["date"].dt.quarter
df["Semester"] = np.where(df["Quarter"].isin([1,2]), 1,2) # in this jahan 1,2 hogha us main semeter ki jagha 1 aahe gha 
df

,date,Date_Year,Date_Month,Day,Is Weekend,Quarter,Semester
0,2019-12-10,2019,12,Tuesday,0,4,2
1,2018-08-15,2018,8,Wednesday,0,3,2
2,2018-10-23,2018,10,Tuesday,0,4,2
3,2019-08-17,2019,8,Saturday,1,3,2
4,2019-01-06,2019,1,Sunday,1,1,1
...,...,...,...,...,...,...,...
995,2018-10-08,2018,10,Monday,0,4,2
996,2018-12-06,2018,12,Thursday,0,4,2
997,2019-05-07,2019,5,Tuesday,0,2,1
998,2019-03-03,2019,3,Sunday,1,1,1
999,2019-10-15,2019,10,Tuesday,0,4,2