In [1]:
import pandas as pd

In [7]:
data = { "Name" : ["Shahzaib", "Ali", "Sahran", "Asad", "Asif", "Assar", "Salman", "Shireen"], 
                   "Age" : [24,15, None,20, 22, 48, None,60], 
                    "Salary" :[1500, 100, None , 2000,None, 2500, 1200,None]
       }

In [8]:
df =pd.DataFrame(data)
print("Orignal Data")
df

Orignal Data

       Name   Age  Salary
0  Shahzaib  24.0  1500.0
1       Ali  15.0   100.0
2    Sahran   NaN     NaN
3      Asad  20.0  2000.0
4      Asif  22.0     NaN
5     Assar  48.0  2500.0
6    Salman   NaN  1200.0
7   Shireen  60.0     NaN

In [4]:
df.isnull().sum()

Name      0
Age       2
Salary    3
dtype: int64

In [21]:
drop = df.dropna()
print(drop)

       Name   Age  Salary
0  Shahzaib  24.0  1500.0
1       Ali  15.0   100.0
3      Asad  20.0  2000.0
5     Assar  48.0  2500.0

In [22]:
df["Age"] = df["Age"].fillna(df["Age"].mean())  # inplace was not working as fillna doesnt work with slicing
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df

       Name   Age  Salary
0  Shahzaib  24.0  1500.0
1       Ali  15.0   100.0
2    Sahran  31.5  1460.0
3      Asad  20.0  2000.0
4      Asif  22.0  1460.0
5     Assar  48.0  2500.0
6    Salman  31.5  1200.0
7   Shireen  60.0  1460.0

In [23]:
df.isnull().sum()

Name      0
Age       0
Salary    0
dtype: int64

In [24]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\asifb\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn) (2.4.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 12.6 MB/s eta 0:00:01
   --- ------------------------------------ 0.8/8.1 MB 2.5 MB/s eta 0:00:03
   ----- ---------------------------------- 1.0/8.1 MB 1.8 MB/s eta 0:00:04
   ------ --------------------------------- 1.3/8.1 MB 1.5 MB/s eta 0:00:05
   ------ --------------------------------- 1.3/8.1 MB 1.5 MB/s eta 0:00:05
   ------- -------------------------------- 1.6/8.1 MB 1.3 MB/s eta 0:00:06
   --------- ------------------------------ 1.8/8.1 MB 1.2 MB/s eta 0:00:06
   ---------- ----------------------------- 2.1/8.1 MB 1.2 MB/s eta 0:00:06
   ----------- ---------------------------- 2.4/8.1 MB 1.2 MB/s eta 0:00:05
   ------------ --------------------------- 2.6/8.1 MB 1.1 MB/s eta 0:00:05
   ------------ --------------------------- 2.6/8.1 MB 1.1 MB/s eta 0:00:05
   -------------- ------------------------- 2.9/8.1 MB 1.1 MB/s eta 0:00:05
   -------------- ------------------------- 2.9/8.1 MB 1.1 MB/s eta 0:00:05
   --------------- ------------------------ 3.1/8.1 MB 1.1 MB/s eta 0:00:05
   ---------------- ----------------------- 3.4/8.1 MB 1.0 MB/s eta 0:00:05
   ---------------- ----------------------- 3.4/8.1 MB 1.0 MB/s eta 0:00:05
   ------------------ --------------------- 3.7/8.1 MB 1.0 MB/s eta 0:00:05
   ------------------- -------------------- 3.9/8.1 MB 1.0 MB/s eta 0:00:05
   ---------------------- ----------------- 4.5/8.1 MB 1.1 MB/s eta 0:00:04
   ----------------------- ---------------- 4.7/8.1 MB 1.1 MB/s eta 0:00:04
   ----------------------- ---------------- 4.7/8.1 MB 1.1 MB/s eta 0:00:04
   ------------------------ --------------- 5.0/8.1 MB 1.1 MB/s eta 0:00:03
   ------------------------- -------------- 5.2/8.1 MB 1.0 MB/s eta 0:00:03
   ------------------------- -------------- 5.2/8.1 MB 1.0 MB/s eta 0:00:03
   --------------------------- ------------ 5.5/8.1 MB 1.0 MB/s eta 0:00:03
   ---------------------------- ----------- 5.8/8.1 MB 1.0 MB/s eta 0:00:03
   ----------------------------- ---------- 6.0/8.1 MB 1.0 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.1 MB 1.0 MB/s eta 0:00:02
   ------------------------------- -------- 6.3/8.1 MB 1.0 MB/s eta 0:00:02
   -------------------------------- ------- 6.6/8.1 MB 1.0 MB/s eta 0:00:02
   --------------------------------- ------ 6.8/8.1 MB 1.0 MB/s eta 0:00:02
   --------------------------------- ------ 6.8/8.1 MB 1.0 MB/s eta 0:00:02
   ---------------------------------- ----- 7.1/8.1 MB 1.0 MB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.1 MB 1.0 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 1.0 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 1.0 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 1.0 MB/s  0:00:07
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.3 MB ? eta -:--:--
    --------------------------------------- 0.5/37.3 MB 594.8 kB/s eta 0:01:02
    --------------------------------------- 0.5/37.3 MB 594.8 kB/s eta 0:01:02
    --------------------------------------- 0.8/37.3 MB 712.4 kB/s eta 0:00:52
   - -------------------------------------- 1.0/37.3 MB 792.7 kB/s eta 0:00:46
   - -------------------------------------- 1.3/37.3 MB 865.5 kB/s eta 0:00:42
   - -------------------------------------- 1.6/37.3 MB 946.1 kB/s eta 0:00:38
   - -------------------------------------- 1.8/37.3 MB 990.4 kB/s eta 0:00:36
   -- ------------------------------------- 2.1/37.3 MB 1.0 MB/s eta 0:00:35
   -- ------------------------------------- 2.1/37.3 MB 1.0 MB/s eta 0:00:35
   -- ------------------------------------- 2.4/37.3 MB 926.6 kB/s eta 0:00:38
   -- ------------------------------------- 2.4/37.3 MB 926.6 kB/s eta 0:00:38
   -- ------------------------------------- 2.4/37.3 MB 926.6 kB/s eta 0:00:38
   -- ------------------------------------- 2.6/37.3 MB 817.5 kB/s eta 0:00:43
   -- ------------------------------------- 2.6/37.3 MB 817.5 kB/s eta 0:00:43
   --- ------------------------------------ 2.9/37.3 MB 771.4 kB/s eta 0:00:45
   --- ------------------------------------ 2.9/37.3 MB 771.4 kB/s eta 0:00:45
   --- ------------------------------------ 3.1/37.3 MB 757.3 kB/s eta 0:00:46
   --- ------------------------------------ 3.1/37.3 MB 757.3 kB/s eta 0:00:46
   --- ------------------------------------ 3.4/37.3 MB 753.9 kB/s eta 0:00:45
   --- ------------------------------------ 3.4/37.3 MB 753.9 kB/s eta 0:00:45
   --- ------------------------------------ 3.7/37.3 MB 736.4 kB/s eta 0:00:46
   --- ------------------------------------ 3.7/37.3 MB 736.4 kB/s eta 0:00:46
   ---- ----------------------------------- 3.9/37.3 MB 728.7 kB/s eta 0:00:46
   ---- ----------------------------------- 3.9/37.3 MB 728.7 kB/s eta 0:00:46
   ---- ----------------------------------- 4.2/37.3 MB 727.5 kB/s eta 0:00:46
   ---- ----------------------------------- 4.2/37.3 MB 727.5 kB/s eta 0:00:46
   ---- ----------------------------------- 4.5/37.3 MB 729.0 kB/s eta 0:00:46
   ----- ---------------------------------- 4.7/37.3 MB 741.6 kB/s eta 0:00:44
   ----- ---------------------------------- 5.0/37.3 MB 741.1 kB/s eta 0:00:44
   ----- ---------------------------------- 5.0/37.3 MB 741.1 kB/s eta 0:00:44
   ----- ---------------------------------- 5.2/37.3 MB 746.1 kB/s eta 0:00:43
   ----- ---------------------------------- 5.5/37.3 MB 750.7 kB/s eta 0:00:43
   ----- ---------------------------------- 5.5/37.3 MB 750.7 kB/s eta 0:00:43
   ------ --------------------------------- 5.8/37.3 MB 754.9 kB/s eta 0:00:42
   ------ --------------------------------- 6.0/37.3 MB 759.0 kB/s eta 0:00:42
   ------ --------------------------------- 6.0/37.3 MB 759.0 kB/s eta 0:00:42
   ------ --------------------------------- 6.3/37.3 MB 762.6 kB/s eta 0:00:41
   ------- -------------------------------- 6.6/37.3 MB 765.9 kB/s eta 0:00:41
   ------- -------------------------------- 6.8/37.3 MB 778.3 kB/s eta 0:00:40
   ------- -------------------------------- 7.1/37.3 MB 790.4 kB/s eta 0:00:39
   ------- -------------------------------- 7.1/37.3 MB 790.4 kB/s eta 0:00:39
   ------- -------------------------------- 7.3/37.3 MB 792.6 kB/s eta 0:00:38
   -------- ------------------------------- 7.6/37.3 MB 803.3 kB/s eta 0:00:37
   -------- ------------------------------- 7.9/37.3 MB 805.2 kB/s eta 0:00:37
   -------- ------------------------------- 8.1/37.3 MB 815.3 kB/s eta 0:00:36
   -------- ------------------------------- 8.4/37.3 MB 824.9 kB/s eta 0:00:36
   --------- ------------------------------ 8.7/37.3 MB 834.2 kB/s eta 0:00:35
   --------- ------------------------------ 9.2/37.3 MB 859.8 kB/s eta 0:00:33
   --------- ------------------------------ 9.2/37.3 MB 859.8 kB/s eta 0:00:33
   ---------- ----------------------------- 9.4/37.3 MB 859.8 kB/s eta 0:00:33
   ---------- ----------------------------- 9.7/37.3 MB 867.8 kB/s eta 0:00:32
   ---------- ----------------------------- 9.7/37.3 MB 867.8 kB/s eta 0:00:32
   ---------- ----------------------------- 10.0/37.3 MB 852.9 kB/s eta 0:00:33
   ---------- ----------------------------- 10.0/37.3 MB 852.9 kB/s eta 0:00:33
   ---------- ----------------------------- 10.2/37.3 MB 844.5 kB/s eta 0:00:33
   ---------- ----------------------------- 10.2/37.3 MB 844.5 kB/s eta 0:00:33
   ----------- ---------------------------- 10.5/37.3 MB 837.5 kB/s eta 0:00:33
   ----------- ---------------------------- 10.5/37.3 MB 837.5 kB/s eta 0:00:33
   ----------- ---------------------------- 10.7/37.3 MB 831.1 kB/s eta 0:00:32
   ----------- ---------------------------- 11.0/37.3 MB 831.7 kB/s eta 0:00:32
   ----------- ---------------------------- 11.0/37.3 MB 831.7 kB/s eta 0:00:32
   ------------ --------------------------- 11.3/37.3 MB 825.9 kB/s eta 0:00:32
   ------------ --------------------------- 11.3/37.3 MB 825.9 kB/s eta 0:00:32
   ------------ --------------------------- 11.5/37.3 MB 826.4 kB/s eta 0:00:32
   ------------ --------------------------- 11.8/37.3 MB 827.1 kB/s eta 0:00:31
   ------------ --------------------------- 11.8/37.3 MB 827.1 kB/s eta 0:00:31
   ------------ --------------------------- 12.1/37.3 MB 821.8 kB/s eta 0:00:31
   ------------ --------------------------- 12.1/37.3 MB 821.8 kB/s eta 0:00:31
   ------------- -------------------------- 12.3/37.3 MB 822.5 kB/s eta 0:00:31
   ------------- -------------------------- 12.6/37.3 MB 822.8 kB/s eta 0:00:31
   ------------- -------------------------- 12.8/37.3 MB 825.8 kB/s eta 0:00:30
   -------------- ------------------------- 13.1/37.3 MB 829.5 kB/s eta 0:00:30
   -------------- ------------------------- 13.1/37.3 MB 829.5 kB/s eta 0:00:30
   -------------- ------------------------- 13.4/37.3 MB 830.1 kB/s eta 0:00:29
   -------------- ------------------------- 13.6/37.3 MB 830.6 kB/s eta 0:00:29
   -------------- ------------------------- 13.9/37.3 MB 836.1 kB/s eta 0:00:28
   -------------- ------------------------- 13.9/37.3 MB 836.1 kB/s eta 0:00:28
   --------------- ------------------------ 14.2/37.3 MB 836.5 kB/s eta 0:00:28
   --------------- ------------------------ 14.4/37.3 MB 841.9 kB/s eta 0:00:28
   --------------- ------------------------ 14.7/37.3 MB 842.1 kB/s eta 0:00:27
   ---------------- ----------------------- 14.9/37.3 MB 848.2 kB/s eta 0:00:27
   ---------------- ----------------------- 15.2/37.3 MB 852.3 kB/s eta 0:00:26
   ---------------- ----------------------- 15.5/37.3 MB 857.2 kB/s eta 0:00:26
   ---------------- ----------------------- 15.7/37.3 MB 857.3 kB/s eta 0:00:26
   ----------------- ---------------------- 16.0/37.3 MB 861.9 kB/s eta 0:00:25
   ----------------- ---------------------- 16.0/37.3 MB 861.9 kB/s eta 0:00:25
   ----------------- ---------------------- 16.3/37.3 MB 861.9 kB/s eta 0:00:25
   ----------------- ---------------------- 16.8/37.3 MB 877.4 kB/s eta 0:00:24
   ----------------- ---------------------- 16.8/37.3 MB 877.4 kB/s eta 0:00:24
   ------------------ --------------------- 17.0/37.3 MB 875.3 kB/s eta 0:00:24
   ------------------ --------------------- 17.3/37.3 MB 874.9 kB/s eta 0:00:23
   ------------------ --------------------- 17.6/37.3 MB 877.5 kB/s eta 0:00:23
   ------------------ --------------------- 17.6/37.3 MB 877.5 kB/s eta 0:00:23
   ------------------ --------------------- 17.6/37.3 MB 877.5 kB/s eta 0:00:23
   ------------------- -------------------- 17.8/37.3 MB 869.8 kB/s eta 0:00:23
   ------------------- -------------------- 17.8/37.3 MB 869.8 kB/s eta 0:00:23
   ------------------- -------------------- 18.1/37.3 MB 860.9 kB/s eta 0:00:23
   ------------------- -------------------- 18.1/37.3 MB 860.9 kB/s eta 0:00:23
   ------------------- -------------------- 18.4/37.3 MB 856.7 kB/s eta 0:00:23
   ------------------- -------------------- 18.4/37.3 MB 856.7 kB/s eta 0:00:23
   ------------------- -------------------- 18.6/37.3 MB 852.9 kB/s eta 0:00:22
   ------------------- -------------------- 18.6/37.3 MB 852.9 kB/s eta 0:00:22
   -------------------- ------------------- 18.9/37.3 MB 849.8 kB/s eta 0:00:22
   -------------------- ------------------- 19.1/37.3 MB 848.7 kB/s eta 0:00:22
   -------------------- ------------------- 19.1/37.3 MB 848.7 kB/s eta 0:00:22
   -------------------- ------------------- 19.4/37.3 MB 847.4 kB/s eta 0:00:22
   -------------------- ------------------- 19.4/37.3 MB 847.4 kB/s eta 0:00:22
   --------------------- ------------------ 19.7/37.3 MB 844.9 kB/s eta 0:00:21
   --------------------- ------------------ 19.9/37.3 MB 845.0 kB/s eta 0:00:21
   --------------------- ------------------ 20.2/37.3 MB 845.3 kB/s eta 0:00:21
   --------------------- ------------------ 20.2/37.3 MB 845.3 kB/s eta 0:00:21
   --------------------- ------------------ 20.4/37.3 MB 841.7 kB/s eta 0:00:21
   --------------------- ------------------ 20.4/37.3 MB 841.7 kB/s eta 0:00:21
   ---------------------- ----------------- 20.7/37.3 MB 841.8 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/37.3 MB 841.9 kB/s eta 0:00:20
   ---------------------- ----------------- 21.0/37.3 MB 841.9 kB/s eta 0:00:20
   ---------------------- ----------------- 21.2/37.3 MB 842.4 kB/s eta 0:00:20
   ----------------------- ---------------- 21.5/37.3 MB 842.6 kB/s eta 0:00:19
   ----------------------- ---------------- 21.5/37.3 MB 842.6 kB/s eta 0:00:19
   ----------------------- ---------------- 21.8/37.3 MB 842.4 kB/s eta 0:00:19
   ----------------------- ---------------- 22.0/37.3 MB 845.9 kB/s eta 0:00:19
   ----------------------- ---------------- 22.3/37.3 MB 846.0 kB/s eta 0:00:18
   ----------------------- ---------------- 22.3/37.3 MB 846.0 kB/s eta 0:00:18
   ------------------------ --------------- 22.5/37.3 MB 846.0 kB/s eta 0:00:18
   ------------------------ --------------- 22.8/37.3 MB 849.3 kB/s eta 0:00:18
   ------------------------ --------------- 23.1/37.3 MB 849.4 kB/s eta 0:00:17
   ------------------------- -------------- 23.3/37.3 MB 852.6 kB/s eta 0:00:17
   ------------------------- -------------- 23.9/37.3 MB 862.3 kB/s eta 0:00:16
   ------------------------- -------------- 23.9/37.3 MB 862.3 kB/s eta 0:00:16
   -------------------------- ------------- 24.4/37.3 MB 868.4 kB/s eta 0:00:15
   -------------------------- ------------- 24.6/37.3 MB 871.4 kB/s eta 0:00:15
   -------------------------- ------------- 24.9/37.3 MB 874.4 kB/s eta 0:00:15
   -------------------------- ------------- 24.9/37.3 MB 874.4 kB/s eta 0:00:15
   -------------------------- ------------- 25.2/37.3 MB 874.2 kB/s eta 0:00:14
   -------------------------- ------------- 25.2/37.3 MB 874.2 kB/s eta 0:00:14
   --------------------------- ------------ 25.4/37.3 MB 870.8 kB/s eta 0:00:14
   --------------------------- ------------ 25.7/37.3 MB 871.0 kB/s eta 0:00:14
   --------------------------- ------------ 26.0/37.3 MB 870.5 kB/s eta 0:00:14
   --------------------------- ------------ 26.0/37.3 MB 870.5 kB/s eta 0:00:14
   ---------------------------- ----------- 26.2/37.3 MB 867.3 kB/s eta 0:00:13
   ---------------------------- ----------- 26.2/37.3 MB 867.3 kB/s eta 0:00:13
   ---------------------------- ----------- 26.5/37.3 MB 868.2 kB/s eta 0:00:13
   ---------------------------- ----------- 26.5/37.3 MB 868.2 kB/s eta 0:00:13
   ---------------------------- ----------- 26.7/37.3 MB 863.6 kB/s eta 0:00:13
   ---------------------------- ----------- 26.7/37.3 MB 863.6 kB/s eta 0:00:13
   ---------------------------- ----------- 27.0/37.3 MB 861.1 kB/s eta 0:00:12
   ---------------------------- ----------- 27.0/37.3 MB 861.1 kB/s eta 0:00:12
   ----------------------------- ---------- 27.3/37.3 MB 851.4 kB/s eta 0:00:12
   ----------------------------- ---------- 27.5/37.3 MB 849.1 kB/s eta 0:00:12
   ----------------------------- ---------- 27.8/37.3 MB 853.0 kB/s eta 0:00:12
   ----------------------------- ---------- 27.8/37.3 MB 853.0 kB/s eta 0:00:12
   ------------------------------ --------- 28.0/37.3 MB 862.1 kB/s eta 0:00:11
   ------------------------------ --------- 28.3/37.3 MB 862.1 kB/s eta 0:00:11
   ------------------------------ --------- 28.3/37.3 MB 862.1 kB/s eta 0:00:11
   ------------------------------ --------- 28.6/37.3 MB 868.6 kB/s eta 0:00:11
   ------------------------------ --------- 28.8/37.3 MB 870.9 kB/s eta 0:00:10
   ------------------------------- -------- 29.1/37.3 MB 873.9 kB/s eta 0:00:10
   ------------------------------- -------- 29.1/37.3 MB 873.9 kB/s eta 0:00:10
   ------------------------------- -------- 29.4/37.3 MB 875.5 kB/s eta 0:00:10
   ------------------------------- -------- 29.6/37.3 MB 875.3 kB/s eta 0:00:09
   -------------------------------- ------- 29.9/37.3 MB 882.7 kB/s eta 0:00:09
   -------------------------------- ------- 29.9/37.3 MB 882.7 kB/s eta 0:00:09
   -------------------------------- ------- 30.1/37.3 MB 885.7 kB/s eta 0:00:09
   -------------------------------- ------- 30.4/37.3 MB 885.4 kB/s eta 0:00:08
   -------------------------------- ------- 30.7/37.3 MB 890.3 kB/s eta 0:00:08
   --------------------------------- ------ 31.2/37.3 MB 901.2 kB/s eta 0:00:07
   ---------------------------------- ----- 31.7/37.3 MB 911.6 kB/s eta 0:00:07
   ---------------------------------- ----- 31.7/37.3 MB 911.6 kB/s eta 0:00:07
   ---------------------------------- ----- 31.7/37.3 MB 911.6 kB/s eta 0:00:07
   ---------------------------------- ----- 31.7/37.3 MB 911.6 kB/s eta 0:00:07
   ---------------------------------- ----- 32.0/37.3 MB 895.8 kB/s eta 0:00:06
   ---------------------------------- ----- 32.0/37.3 MB 895.8 kB/s eta 0:00:06
   ---------------------------------- ----- 32.0/37.3 MB 895.8 kB/s eta 0:00:06
   ---------------------------------- ----- 32.0/37.3 MB 895.8 kB/s eta 0:00:06
   ---------------------------------- ----- 32.0/37.3 MB 895.8 kB/s eta 0:00:06
   ---------------------------------- ----- 32.2/37.3 MB 876.8 kB/s eta 0:00:06
   ---------------------------------- ----- 32.2/37.3 MB 876.8 kB/s eta 0:00:06
   ---------------------------------- ----- 32.2/37.3 MB 876.8 kB/s eta 0:00:06
   ---------------------------------- ----- 32.2/37.3 MB 876.8 kB/s eta 0:00:06
   ---------------------------------- ----- 32.5/37.3 MB 860.7 kB/s eta 0:00:06
   ----------------------------------- ---- 32.8/37.3 MB 856.6 kB/s eta 0:00:06
   ----------------------------------- ---- 32.8/37.3 MB 856.6 kB/s eta 0:00:06
   ----------------------------------- ---- 33.0/37.3 MB 850.6 kB/s eta 0:00:06
   ----------------------------------- ---- 33.0/37.3 MB 850.6 kB/s eta 0:00:06
   ----------------------------------- ---- 33.0/37.3 MB 850.6 kB/s eta 0:00:06
   ----------------------------------- ---- 33.3/37.3 MB 841.7 kB/s eta 0:00:05
   ----------------------------------- ---- 33.3/37.3 MB 841.7 kB/s eta 0:00:05
   ----------------------------------- ---- 33.6/37.3 MB 826.9 kB/s eta 0:00:05
   ----------------------------------- ---- 33.6/37.3 MB 826.9 kB/s eta 0:00:05
   ------------------------------------ --- 33.8/37.3 MB 818.2 kB/s eta 0:00:05
   ------------------------------------ --- 33.8/37.3 MB 818.2 kB/s eta 0:00:05
   ------------------------------------ --- 34.1/37.3 MB 814.5 kB/s eta 0:00:04
   ------------------------------------ --- 34.1/37.3 MB 814.5 kB/s eta 0:00:04
   ------------------------------------ --- 34.3/37.3 MB 814.9 kB/s eta 0:00:04
   ------------------------------------ --- 34.3/37.3 MB 814.9 kB/s eta 0:00:04
   ------------------------------------ --- 34.3/37.3 MB 814.9 kB/s eta 0:00:04
   ------------------------------------- -- 34.6/37.3 MB 812.2 kB/s eta 0:00:04
   ------------------------------------- -- 34.6/37.3 MB 812.2 kB/s eta 0:00:04
   ------------------------------------- -- 34.6/37.3 MB 812.2 kB/s eta 0:00:04
   ------------------------------------- -- 34.6/37.3 MB 812.2 kB/s eta 0:00:04
   ------------------------------------- -- 34.6/37.3 MB 812.2 kB/s eta 0:00:04

[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: C:\Users\asifb\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [5]:
df

       Name   Age  Salary
0  Shahzaib  24.0  1500.0
1       Ali  15.0   100.0
2    Sahran   NaN     NaN
3      Asad  20.0  2000.0
4      Asif  22.0     NaN
5     Assar  48.0  2500.0
6    Salman   NaN  1200.0
7   Shireen  60.0     NaN

In [6]:
df.isnull().sum()

Name      0
Age       2
Salary    3
dtype: int64

In [7]:
df[df["Name"] ==  "Shahzaib"]["Salary"]

0    1500.0
Name: Salary, dtype: float64

In [5]:
df = df.dropna()

In [6]:
df

       Name   Age  Salary
0  Shahzaib  24.0  1500.0
1       Ali  15.0   100.0
3      Asad  20.0  2000.0
5     Assar  48.0  2500.0

In [9]:
df

       Name   Age  Salary
0  Shahzaib  24.0  1500.0
1       Ali  15.0   100.0
2    Sahran   NaN     NaN
3      Asad  20.0  2000.0
4      Asif  22.0     NaN
5     Assar  48.0  2500.0
6    Salman   NaN  1200.0
7   Shireen  60.0     NaN

## filling NA values

In [13]:
df["Age"] =df["Age"].fillna(df["Age"].mean())

In [14]:
df

       Name   Age  Salary
0  Shahzaib  24.0  1500.0
1       Ali  15.0   100.0
2    Sahran  31.5     NaN
3      Asad  20.0  2000.0
4      Asif  22.0     NaN
5     Assar  48.0  2500.0
6    Salman  31.5  1200.0
7   Shireen  60.0     NaN

In [15]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

In [16]:
df

       Name   Age  Salary
0  Shahzaib  24.0  1500.0
1       Ali  15.0   100.0
2    Sahran  31.5  1460.0
3      Asad  20.0  2000.0
4      Asif  22.0  1460.0
5     Assar  48.0  2500.0
6    Salman  31.5  1200.0
7   Shireen  60.0  1460.0

In [20]:
print(df.isnull().mean() * 100 )

Name      0.0
Age       0.0
Salary    0.0
dtype: float64

# Machine Learning Start

##### Preprocessing is the section from which you are importing label encoder

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
import pandas as pd

In [24]:
data = {"Name" : ["Asif", "Shahzaib" , "Salman", "Arfa" ,"Sahran" , "Shireen" , "Inza" ], 
        "Gender" : ["Male" ,"Male" ,"Male" ,"Female" ,"Male" , "Female","Female"]}

In [27]:
data.keys()

dict_keys(['Name', 'Gender'])

In [28]:
df  = pd.DataFrame(data)
df

       Name  Gender
0      Asif    Male
1  Shahzaib    Male
2    Salman    Male
3      Arfa  Female
4    Sahran    Male
5   Shireen  Female
6      Inza  Female

In [29]:
label = df.copy()

In [32]:
le = LabelEncoder()

In [33]:
label["Gender_Encoded"] = le.fit_transform(label["Gender"])

In [34]:
label

       Name  Gender  Gender_Encoded
0      Asif    Male               1
1  Shahzaib    Male               1
2    Salman    Male               1
3      Arfa  Female               0
4    Sahran    Male               1
5   Shireen  Female               0
6      Inza  Female               0

#### One Hot encoding

In [39]:
label["City"] = ["Karachi", "Lahore", "Islamabad", "Karachi", "Lahore", "Peshawar", "Quetta"]

In [40]:
label

       Name  Gender  Gender_Encoded       City
0      Asif    Male               1    Karachi
1  Shahzaib    Male               1     Lahore
2    Salman    Male               1  Islamabad
3      Arfa  Female               0    Karachi
4    Sahran    Male               1     Lahore
5   Shireen  Female               0   Peshawar
6      Inza  Female               0     Quetta

In [42]:
hot_encoded = pd.get_dummies(label , columns = ["City"] , dtype = int)
print("\n One Hot encoded Data (city)")
print(hot_encoded)

 One Hot encoded Data (city)
       Name  Gender  Gender_Encoded  City_Islamabad  City_Karachi  \
0      Asif    Male               1               0             1
1  Shahzaib    Male               1               0             0
2    Salman    Male               1               1             0
3      Arfa  Female               0               0             1
4    Sahran    Male               1               0             0
5   Shireen  Female               0               0             0
6      Inza  Female               0               0             0

   City_Lahore  City_Peshawar  City_Quetta
0            0              0            0
1            1              0            0
2            0              0            0
3            0              0            0
4            1              0            0
5            0              1            0
6            0              0            1

### Feature Scalling

In [44]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler 
from sklearn.model_selection import train_test_split

In [45]:
data = { "Study_Hours" : [5 ,10 ,15 ,20] , "Marks" : [50,60,70,80]}

In [46]:
df = pd.DataFrame(data)

In [52]:
SS = StandardScaler()    # ye values nikale gha

In [54]:
standard_scaled = SS.fit_transform(df)   # ye mean and SD nikale gha aur formula lagahe gha aur scale kare gha for each value

In [55]:
print(pd.DataFrame(standard_scaled, columns = ["Study_Hours" , "Marks"]))    # humne columns define kar liye

   Study_Hours     Marks
0    -1.341641 -1.341641
1    -0.447214 -0.447214
2     0.447214  0.447214
3     1.341641  1.341641

In [56]:
Min_max = MinMaxScaler()

In [59]:
MMScaled = Min_max.fit_transform(df)

In [62]:
print(pd.DataFrame(MMScaled , columns = ["Study_Hours" , "Marks"])) # range b/w 0 -1

   Study_Hours     Marks
0     0.000000  0.000000
1     0.333333  0.333333
2     0.666667  0.666667
3     1.000000  1.000000

#### Train test and split

In [65]:
df[["Study_Hours"]]            # one bracket --> array. 2 brackets --> Data frame

   Study_Hours
0            5
1           10
2           15
3           20

In [67]:
X = df[["Study_Hours"]]      # input 
Y = df[["Marks"]]            # output

In [68]:
X_train , X_test , Y_train , Y_test = train_test_split(X,Y , test_size = 0.2 , random_state = 42)

In [70]:
print("Training Data")
print(X_train)
print("-" * 50)
print("Test Data")
print(X_test)
print("Training Data Y")
print(Y_train)
print("-" *50)
print("Test Data Y")
print(Y_test)

Training Data
   Study_Hours
3           20
0            5
2           15
--------------------------------------------------
Test Data
   Study_Hours
1           10
Training Data Y
   Marks
3     80
0     50
2     70
--------------------------------------------------
Test Data Y
   Marks
1     60

In [72]:
# the 60 is predicted by the model and actual is also 60 so the model is correct

### Linear Regression

In [73]:
from sklearn.linear_model import LinearRegression

In [78]:
Model = LinearRegression()
x = [[1] , [2],[3], [4]]
y = [50,60,70,80]
Model.fit(x,y)
hours = float(input("Enter how many hours you studied :"))
Predicted_Marks = Model.predict([[hours]])

print(f"Based on hours to study {hours} you may score around {Predicted_Marks}")

Enter how many hours you studied : 5.6

Based on hours to study 5.6 you may score around [96.]

In [79]:
from sklearn.linear_model import LogisticRegression

In [89]:
X = [[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]]        # input --> hours studied
Y =  [0,  0,  0,  0,  1,  1,  1,  1,  1,  1]         # output  --> result of pass and fail

Model = LogisticRegression()
Model.fit(X,Y)
hours = float(input("Enter how many hours you studied :"))
Result = Model.predict([[hours]])[0]        # to get answer in either 0 or 1

if Result == 1:
    print(f" Based on {hours} hours studied, you are likely to PASS")

else :
    print(f" Based on {hours} hours studied, you are likely to FAIL")

Enter how many hours you studied : 4.9

 Based on 4.9 hours studied, you are likely to PASS

### KNN

In [2]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
X = [
[180,7], [200,7.5], [250,8],[300,8.5],[330,9], [360,9.5]    
]

# 0 = Apple and 1 = Organge 
Y  = [0 ,0,0,1,1,1]

Model = KNeighborsClassifier(n_neighbors = 3)

Model.fit(X,Y)

weight= float(input("Enter the weight in grams:"))

Size = float(input("Enter the size in CM:"))
             
prediction = Model.predict([[weight , Size]])[0]     # why we have put [0] if we havent done this the model would give [0] or [1] by pitting [0] we get
                                                     # value inside the brackets which we would use in if statements 
if prediction == 0:
    print("This is likely an apple")
else :
    print("This is likely an orange")

Enter the weight in grams: 280.98
Enter the size in CM: 11.2

This is likely an orange

### Decision Tree

In [10]:
from sklearn.tree import DecisionTreeClassifier

X = [
    [7,2] , [9,4] , [10,5] , [11,4] , [14,4] , [15,6] , [17,6] , [19,8] , [18,9] 
]

Y = [0,0,0,0,1,1,1,1,1]   # 0 = apple and 1 = orange 

Model = DecisionTreeClassifier()

Model.fit(X,Y)

Size = float(input("Enter the fruit size in grams:"))
Shade = float(input("Enter the fruit color shade (1-10):"))

result= Model.predict([[Size , Shade]])[0]

if result == 0 :
    print("This is likely an apple")
else :
    print("This is likely an orange")

Enter the fruit size in grams: 7.8
Enter the fruit color shade (1-10): 8

This is likely an apple

## Classification Metrics 
###### To score/measure the model. How correct the model is.

In [12]:
from sklearn.metrics import accuracy_score, recall_score , precision_score, f1_score

In [13]:
# True answers (what happened actually)
X_true = [1,1,0,0,1,0,1]
# what it guessed
X_predict = [1,1,1,0,0,0,1]

print("Accuracy" , accuracy_score(X_true , X_predict))
print("Recall" , recall_score(X_true , X_predict))
print("Precision" , precision_score(X_true , X_predict))
print("F1_Score" , f1_score(X_true , X_predict))

Accuracy 0.7142857142857143
Recall 0.75
Precision 0.75
F1_Score 0.75

In [17]:
from sklearn.metrics import confusion_matrix

In [20]:
y_true =    [1,1,0,1,0,0,1,1,0]    

y_predict = [1,0,0,1,0,1,0,1,0]      # 3 mistakes were made (2 + 1) 

CM = confusion_matrix(y_true , y_predict)

print("Confussion Matrix")
print(CM)

Confussion Matrix
[[3 1]
 [2 3]]

In [1]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

In [6]:
Actual = [90, 60,80,100]
Predicted = [85, 70,70, 95] 

MAE = mean_absolute_error(Actual , Predicted)
MSE = mean_squared_error(Actual , Predicted)
RMSE = np.sqrt(MSE)
print("MAE:" , MAE)
print("MSE:" , MSE)
print("RMSE:",RMSE)

MAE: 7.5
MSE: 62.5
RMSE: 7.905694150420948

## Project # 1

In [7]:
import pandas as pd 
from sklearn.linear_model import LinearRegression
import numpy as np 
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [9]:
df =pd.read_csv(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Kaggle\Hosuing Kaggle.csv")

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  int64
 3   total_rooms         20640 non-null  int64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  int64
 6   households          20640 non-null  int64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  str
 9   ocean_proximity     20640 non-null  str
dtypes: float64(4), int64(4), str(2)
memory usage: 1.6 MB

In [15]:
df["median_house_value"] = df["median_house_value"].str.replace("," ,"")
df["median_house_value"] = df["median_house_value"].astype(float)

In [18]:
df["total_bedrooms"] = df["total_bedrooms"].fillna(df["total_bedrooms"].median())